# Generated by Django 4.1.6 on 2023-02-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('get_vendors', '0005_delete_user'),
        ('zipcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_vendors.vendor')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipcode.zipcode')),
            ],
            options={
                'ordering': ['vendor'],
            },
        ),
    ]
