# Generated by Django 4.1.6 on 2023-02-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_zipcode',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
