# Generated by Django 4.1.6 on 2023-02-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='zip_code',
        ),
    ]
