# Generated by Django 4.1.6 on 2023-02-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_vendors', '0002_remove_vendor_address_remove_vendor_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
