# Generated by Django 4.1.6 on 2023-02-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_vendors', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
