# Generated by Django 4.1.6 on 2023-02-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_vendors', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='zip_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
